# Generated by Django 3.2.9 on 2021-12-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_note_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='title',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=models.TextField(max_length=280),
        ),
    ]
